#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    
    #line 2 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/GitCandy/Views/User/_List_Data.cshtml")]
    public partial class _Areas_GitCandy_Views_User__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<NewLife.GitCandy.Entity.User>>
    {
        public _Areas_GitCandy_Views_User__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var enableSelect = this.EnableSelect();
    var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 829), Tuple.Create("\"", 868)
            
            #line 24 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 836), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 836), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"名称。登录用户名\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 938), Tuple.Create("\"", 979)
            
            #line 25 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 945), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 945), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"显示名。昵称、中文名等\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1052), Tuple.Create("\"", 1097)
            
            #line 26 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1059), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("NickName"))
            
            #line default
            #line hidden
, 1059), false)
);

WriteLiteral(">显示名</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1151), Tuple.Create("\"", 1193)
            
            #line 27 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Email"))
            
            #line default
            #line hidden
, 1158), false)
);

WriteLiteral(">邮件</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1246), Tuple.Create("\"", 1289)
            
            #line 28 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1253), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1253), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1342), Tuple.Create("\"", 1385)
            
            #line 29 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1349), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("IsTeam"))
            
            #line default
            #line hidden
, 1349), false)
);

WriteLiteral(">团队</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1438), Tuple.Create("\"", 1482)
            
            #line 30 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1445), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("IsAdmin"))
            
            #line default
            #line hidden
, 1445), false)
);

WriteLiteral(">管理员</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1536), Tuple.Create("\"", 1579)
            
            #line 31 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1543), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Online"))
            
            #line default
            #line hidden
, 1543), false)
);

WriteLiteral(">在线</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1657), Tuple.Create("\"", 1706)
            
            #line 32 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1664), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("RegisterTime"))
            
            #line default
            #line hidden
, 1664), false)
);

WriteLiteral(">注册时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1761), Tuple.Create("\"", 1808)
            
            #line 33 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1768), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("RegisterIP"))
            
            #line default
            #line hidden
, 1768), false)
);

WriteLiteral(">注册IP</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1863), Tuple.Create("\"", 1906)
            
            #line 34 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1870), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Logins"))
            
            #line default
            #line hidden
, 1870), false)
);

WriteLiteral(">登录</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1984), Tuple.Create("\"", 2030)
            
            #line 35 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1991), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLogin"))
            
            #line default
            #line hidden
, 1991), false)
);

WriteLiteral(">最后登录</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2085), Tuple.Create("\"", 2133)
            
            #line 36 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2092), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLoginIP"))
            
            #line default
            #line hidden
, 2092), false)
);

WriteLiteral(">最后登录IP</a></th>\r\n");

            
            #line 37 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 40 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 44 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 47 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2600), Tuple.Create("\"", 2618)
            
            #line 49 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2608), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2608), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 50 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 51 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 52 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 53 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.NickName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 54 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.Email);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2921), Tuple.Create("\"", 2983)
, Tuple.Create(Tuple.Create("", 2929), Tuple.Create("glyphicon", 2929), true)
, Tuple.Create(Tuple.Create(" ", 2938), Tuple.Create("glyphicon-", 2939), true)
            
            #line 56 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2949), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 2949), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 2984), Tuple.Create("\"", 3034)
, Tuple.Create(Tuple.Create("", 2992), Tuple.Create("color:", 2992), true)
            
            #line 56 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 2998), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 2999), false)
, Tuple.Create(Tuple.Create("", 3033), Tuple.Create(";", 3033), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3129), Tuple.Create("\"", 3191)
, Tuple.Create(Tuple.Create("", 3137), Tuple.Create("glyphicon", 3137), true)
, Tuple.Create(Tuple.Create(" ", 3146), Tuple.Create("glyphicon-", 3147), true)
            
            #line 59 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3157), Tuple.Create<System.Object, System.Int32>(entity.IsTeam ? "ok" : "remove"
            
            #line default
            #line hidden
, 3157), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3192), Tuple.Create("\"", 3242)
, Tuple.Create(Tuple.Create("", 3200), Tuple.Create("color:", 3200), true)
            
            #line 59 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3206), Tuple.Create<System.Object, System.Int32>(entity.IsTeam ? "green" : "red"
            
            #line default
            #line hidden
, 3207), false)
, Tuple.Create(Tuple.Create("", 3241), Tuple.Create(";", 3241), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3337), Tuple.Create("\"", 3400)
, Tuple.Create(Tuple.Create("", 3345), Tuple.Create("glyphicon", 3345), true)
, Tuple.Create(Tuple.Create(" ", 3354), Tuple.Create("glyphicon-", 3355), true)
            
            #line 62 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3365), Tuple.Create<System.Object, System.Int32>(entity.IsAdmin ? "ok" : "remove"
            
            #line default
            #line hidden
, 3365), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3401), Tuple.Create("\"", 3452)
, Tuple.Create(Tuple.Create("", 3409), Tuple.Create("color:", 3409), true)
            
            #line 62 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                     , Tuple.Create(Tuple.Create(" ", 3415), Tuple.Create<System.Object, System.Int32>(entity.IsAdmin ? "green" : "red"
            
            #line default
            #line hidden
, 3416), false)
, Tuple.Create(Tuple.Create("", 3451), Tuple.Create(";", 3451), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3547), Tuple.Create("\"", 3609)
, Tuple.Create(Tuple.Create("", 3555), Tuple.Create("glyphicon", 3555), true)
, Tuple.Create(Tuple.Create(" ", 3564), Tuple.Create("glyphicon-", 3565), true)
            
            #line 65 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3575), Tuple.Create<System.Object, System.Int32>(entity.Online ? "ok" : "remove"
            
            #line default
            #line hidden
, 3575), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3610), Tuple.Create("\"", 3660)
, Tuple.Create(Tuple.Create("", 3618), Tuple.Create("color:", 3618), true)
            
            #line 65 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3624), Tuple.Create<System.Object, System.Int32>(entity.Online ? "green" : "red"
            
            #line default
            #line hidden
, 3625), false)
, Tuple.Create(Tuple.Create("", 3659), Tuple.Create(";", 3659), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td>");

            
            #line 67 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.RegisterTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 68 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.RegisterIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 69 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                                  Write(entity.Logins.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 70 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.LastLogin.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 71 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
               Write(entity.LastLoginIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 72 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 75 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 77 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 79 "..\..\Areas\GitCandy\Views\User\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
