#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Change.cshtml")]
    public partial class _Views_Account_Change_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.ChangePasswordModel>
    {
        public _Views_Account_Change_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Change.cshtml"
  
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, SR.Account_ChangePasswordTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h3>");

            
            #line 7 "..\..\Views\Account\Change.cshtml"
Write(SR.Account_ChangePasswordTitle);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n");

            
            #line 9 "..\..\Views\Account\Change.cshtml"
 using (Html.BeginForm("Change", "Account", FormMethod.Post))
{

            
            #line default
            #line hidden
WriteLiteral("    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n        <dt>");

            
            #line 12 "..\..\Views\Account\Change.cshtml"
       Write(Html.DisplayNameFor(s => s.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 13 "..\..\Views\Account\Change.cshtml"
       Write(Html.PasswordFor(s => s.OldPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        <dd>\r\n            <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Account\Change.cshtml"
           Write(Html.ValidationMessageFor(s => s.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </dd>\r\n\r\n        <dt>");

            
            #line 20 "..\..\Views\Account\Change.cshtml"
       Write(Html.DisplayNameFor(s => s.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 21 "..\..\Views\Account\Change.cshtml"
       Write(Html.PasswordFor(s => s.NewPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        <dd>\r\n            <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\Change.cshtml"
           Write(Html.ValidationMessageFor(s => s.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </dd>\r\n\r\n        <dt>");

            
            #line 28 "..\..\Views\Account\Change.cshtml"
       Write(Html.DisplayNameFor(s => s.ConformPassword));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 29 "..\..\Views\Account\Change.cshtml"
       Write(Html.PasswordFor(s => s.ConformPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n        <dd>\r\n            <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Account\Change.cshtml"
           Write(Html.ValidationMessageFor(s => s.ConformPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </dd>\r\n\r\n        <dt></dt>\r\n        <dd>\r\n        " +
"    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Account\Change.cshtml"
                                                     Write(SR.Account_ChangePassword);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        </dd>\r\n    </dl>\r\n");

            
            #line 41 "..\..\Views\Account\Change.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
