#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Ssh.cshtml")]
    public partial class _Views_Account_Ssh_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.SshModel>
    {
        public _Views_Account_Ssh_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Ssh.cshtml"
  
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, SR.Account_SshKeys);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>");

            
            #line 7 "..\..\Views\Account\Ssh.cshtml"
Write(SR.Account_SshKeys);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\r\n");

            
            #line 9 "..\..\Views\Account\Ssh.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <span>");

            
            #line 11 "..\..\Views\Account\Ssh.cshtml"
     Write(SR.Account_SSH);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("    <div");

WriteLiteral(" id=\"choose_ssh\"");

WriteLiteral("></div>\r\n");

            
            #line 13 "..\..\Views\Account\Ssh.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var user = \"");

            
            #line 15 "..\..\Views\Account\Ssh.cshtml"
               Write(Model.Username);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var chooser_params = [];\r\n        chooser_params.push(\r\n            {" +
"\r\n                data: ");

            
            #line 19 "..\..\Views\Account\Ssh.cshtml"
                 Write(Html.Raw(new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(Model.SshKeys)));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                container: \"#choose_ssh\",\r\n                add_label: \"");

            
            #line 21 "..\..\Views\Account\Ssh.cshtml"
                       Write(SR.Shared_Add);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                del_label: \"");

            
            #line 22 "..\..\Views\Account\Ssh.cshtml"
                       Write(SR.Shared_Remove);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                use_ret_val: true,\r\n                first_width: 5,\r\n        " +
"        add_action: { url: \"");

            
            #line 25 "..\..\Views\Account\Ssh.cshtml"
                               Write(Url.Action("ChooseSsh", "Account"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { user: user, sshkey: item, act: \"add\" }; } }," +
"\r\n                del_action: { url: \"");

            
            #line 26 "..\..\Views\Account\Ssh.cshtml"
                               Write(Url.Action("ChooseSsh", "Account"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { user: user, sshkey: item, act: \"del\" }; } }," +
"\r\n                action_array: []\r\n            });\r\n    </script>\r\n");

            
            #line 30 "..\..\Views\Account\Ssh.cshtml"
}

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Account\Ssh.cshtml"
Write(Html.ActionLink(SR.Shared_Back, "Detail", new { Name = Model.Username }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
