#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/_BlobPreview.cshtml")]
    public partial class _Views_Repository__BlobPreview_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.TreeEntryModel>
    {
        public _Views_Repository__BlobPreview_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\_BlobPreview.cshtml"
 if (Model.BlobType == BlobType.Text)
{

            
            #line default
            #line hidden
WriteLiteral("    <pre><code");

WriteAttribute("class", Tuple.Create(" class=\"", 97), Tuple.Create("\"", 130)
, Tuple.Create(Tuple.Create("", 105), Tuple.Create("language", 105), true)
            
            #line 5 "..\..\Views\Repository\_BlobPreview.cshtml"
, Tuple.Create(Tuple.Create(" ", 113), Tuple.Create<System.Object, System.Int32>(Model.TextBrush
            
            #line default
            #line hidden
, 114), false)
);

WriteLiteral(">");

            
            #line 5 "..\..\Views\Repository\_BlobPreview.cshtml"
                                            Write(Model.TextContent);

            
            #line default
            #line hidden
WriteLiteral("</code></pre>\r\n");

            
            #line 6 "..\..\Views\Repository\_BlobPreview.cshtml"
}
else if (Model.BlobType == BlobType.MarkDown)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"md\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Repository\_BlobPreview.cshtml"
            Write(Model.TextContent);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 10 "..\..\Views\Repository\_BlobPreview.cshtml"
}
else if (Model.BlobType == BlobType.Image)
{

            
            #line default
            #line hidden
WriteLiteral("    <img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 319), Tuple.Create("\"", 336)
            
            #line 13 "..\..\Views\Repository\_BlobPreview.cshtml"
, Tuple.Create(Tuple.Create("", 325), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 325), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 337), Tuple.Create("\"", 454)
            
            #line 13 "..\..\Views\Repository\_BlobPreview.cshtml"
, Tuple.Create(Tuple.Create("", 343), Tuple.Create<System.Object, System.Int32>(Url.Action("Raw", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Commit.Sha) + "/" + Model.Path }))
            
            #line default
            #line hidden
, 343), false)
);

WriteLiteral(" />\r\n");

            
            #line 14 "..\..\Views\Repository\_BlobPreview.cshtml"
}
else // Binary
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-block\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Repository\_BlobPreview.cshtml"
   Write(SR.Repository_BinaryFileWrods);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Repository\_BlobPreview.cshtml"
   Write(Html.ActionLink(SR.Repository_Raw, "Raw", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Commit.Sha) + "/" + Model.Path })));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 21 "..\..\Views\Repository\_BlobPreview.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
