#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Blob.cshtml")]
    public partial class _Views_Repository_Blob_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.TreeEntryModel>
    {
        public _Views_Repository_Blob_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\Blob.cshtml"
  
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, string.Format(SR.Repository_BlobTitle, Model.RepositoryName, Model.ReferenceName ?? Model.Sha.ToShortSha(), Model.Path));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>");

            
            #line 7 "..\..\Views\Repository\Blob.cshtml"
Write(Html.ActionLink(Model.RepositoryName, "Tree", Html.OverRoute(new { path = "" })));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\r\n");

            
            #line 9 "..\..\Views\Repository\Blob.cshtml"
Write(Html.Partial("_PathBar", Model.PathBar));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Repository\Blob.cshtml"
Write(Html.Partial("_BranchSelector", Model.BranchSelector));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<pre>");

            
            #line 12 "..\..\Views\Repository\Blob.cshtml"
Write(Model.Commit.CommitMessageShort);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 532), Tuple.Create("\"", 560)
            
            #line 15 "..\..\Views\Repository\Blob.cshtml"
, Tuple.Create(Tuple.Create("", 540), Tuple.Create<System.Object, System.Int32>(Model.Commit.Author
            
            #line default
            #line hidden
, 540), false)
);

WriteLiteral(">");

            
            #line 15 "..\..\Views\Repository\Blob.cshtml"
                                        Write(Model.Commit.Author.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n        <span>");

            
            #line 16 "..\..\Views\Repository\Blob.cshtml"
         Write(SR.Repository_AuthoredAt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span");

WriteAttribute("title", Tuple.Create(" title=\"", 659), Tuple.Create("\"", 692)
            
            #line 17 "..\..\Views\Repository\Blob.cshtml"
, Tuple.Create(Tuple.Create("", 667), Tuple.Create<System.Object, System.Int32>(Model.Commit.Author.When
            
            #line default
            #line hidden
, 667), false)
);

WriteLiteral(">");

            
            #line 17 "..\..\Views\Repository\Blob.cshtml"
                                           Write(Model.Commit.Author.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 18 "..\..\Views\Repository\Blob.cshtml"
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Repository\Blob.cshtml"
         if (Model.Commit.Author != Model.Commit.Committer)
        {

            
            #line default
            #line hidden
WriteLiteral("            <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 848), Tuple.Create("\"", 879)
            
            #line 20 "..\..\Views\Repository\Blob.cshtml"
, Tuple.Create(Tuple.Create("", 856), Tuple.Create<System.Object, System.Int32>(Model.Commit.Committer
            
            #line default
            #line hidden
, 856), false)
);

WriteLiteral(">");

            
            #line 20 "..\..\Views\Repository\Blob.cshtml"
                                               Write(Model.Commit.Committer.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n");

WriteLiteral("            <span>");

            
            #line 21 "..\..\Views\Repository\Blob.cshtml"
             Write(SR.Repository_CommittedAt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("            <span");

WriteAttribute("title", Tuple.Create(" title=\"", 990), Tuple.Create("\"", 1026)
            
            #line 22 "..\..\Views\Repository\Blob.cshtml"
, Tuple.Create(Tuple.Create("", 998), Tuple.Create<System.Object, System.Int32>(Model.Commit.Committer.When
            
            #line default
            #line hidden
, 998), false)
);

WriteLiteral(">");

            
            #line 22 "..\..\Views\Repository\Blob.cshtml"
                                                  Write(Model.Commit.Committer.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 23 "..\..\Views\Repository\Blob.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <span>");

            
            #line 28 "..\..\Views\Repository\Blob.cshtml"
         Write(Model.SizeString);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\Repository\Blob.cshtml"
       Write(Html.ActionLink(SR.Repository_History, "Commits", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Sha) + "/" + Model.Path }), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Repository\Blob.cshtml"
       Write(Html.ActionLink(SR.Repository_Blame, "Blame", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Sha) + "/" + Model.Path }), new { @class = "btn btn-default hidden-xs" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Repository\Blob.cshtml"
       Write(Html.ActionLink(SR.Repository_Raw, "Raw", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Sha) + "/" + Model.Path }), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"border-area\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n        <caption>\r\n            <div");

WriteLiteral(" class=\"pull-left keep-space\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-list-alt\"");

WriteLiteral("></i>");

            
            #line 39 "..\..\Views\Repository\Blob.cshtml"
                                                                                     Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </caption>\r\n        <tbody>\r\n            <tr>\r\n                <t" +
"d>\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Views\Repository\Blob.cshtml"
               Write(Html.Partial("_BlobPreview"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n</div" +
">\r\n");

        }
    }
}
#pragma warning restore 1591
