#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Commit.cshtml")]
    public partial class _Views_Repository_Commit_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.CommitModel>
    {
        public _Views_Repository_Commit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\Commit.cshtml"
  
    ViewBag.Title = String.Format(SR.Shared_TitleFormat, String.Format(SR.Repository_CommitTitle, Model.RepositoryName, Model.ReferenceName ?? Model.Sha.ToShortSha(), Model.CommitMessageShort));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>");

            
            #line 7 "..\..\Views\Repository\Commit.cshtml"
Write(Html.ActionLink(Model.RepositoryName, "Tree", Html.OverRoute(new { path = "" })));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\r\n");

            
            #line 9 "..\..\Views\Repository\Commit.cshtml"
Write(Html.Partial("_PathBar", Model.PathBar));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n        <pre>");

            
            #line 13 "..\..\Views\Repository\Commit.cshtml"
        Write(Model.CommitMessage);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n        <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 484), Tuple.Create("\"", 505)
            
            #line 14 "..\..\Views\Repository\Commit.cshtml"
, Tuple.Create(Tuple.Create("", 492), Tuple.Create<System.Object, System.Int32>(Model.Author
            
            #line default
            #line hidden
, 492), false)
);

WriteLiteral(">");

            
            #line 14 "..\..\Views\Repository\Commit.cshtml"
                                 Write(Model.Author.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n        <span>");

            
            #line 15 "..\..\Views\Repository\Commit.cshtml"
         Write(SR.Repository_AuthoredAt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span");

WriteAttribute("title", Tuple.Create(" title=\"", 597), Tuple.Create("\"", 623)
            
            #line 16 "..\..\Views\Repository\Commit.cshtml"
, Tuple.Create(Tuple.Create("", 605), Tuple.Create<System.Object, System.Int32>(Model.Author.When
            
            #line default
            #line hidden
, 605), false)
);

WriteLiteral(">");

            
            #line 16 "..\..\Views\Repository\Commit.cshtml"
                                    Write(Model.Author.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 17 "..\..\Views\Repository\Commit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Repository\Commit.cshtml"
         if (Model.Author != Model.Committer)
        {

            
            #line default
            #line hidden
WriteLiteral("            <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 758), Tuple.Create("\"", 782)
            
            #line 19 "..\..\Views\Repository\Commit.cshtml"
, Tuple.Create(Tuple.Create("", 766), Tuple.Create<System.Object, System.Int32>(Model.Committer
            
            #line default
            #line hidden
, 766), false)
);

WriteLiteral(">");

            
            #line 19 "..\..\Views\Repository\Commit.cshtml"
                                        Write(Model.Committer.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n");

WriteLiteral("            <span>");

            
            #line 20 "..\..\Views\Repository\Commit.cshtml"
             Write(SR.Repository_CommittedAt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("            <span");

WriteAttribute("title", Tuple.Create(" title=\"", 886), Tuple.Create("\"", 915)
            
            #line 21 "..\..\Views\Repository\Commit.cshtml"
, Tuple.Create(Tuple.Create("", 894), Tuple.Create<System.Object, System.Int32>(Model.Committer.When
            
            #line default
            #line hidden
, 894), false)
);

WriteLiteral(">");

            
            #line 21 "..\..\Views\Repository\Commit.cshtml"
                                           Write(Model.Committer.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 22 "..\..\Views\Repository\Commit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"col-md-3 text-right\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Repository\Commit.cshtml"
                 Write(Html.ActionLink(Model.Sha.ToShortSha(), "Commit", Html.OverRoute(new { path = Model.Sha })));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Repository\Commit.cshtml"
                 Write(Html.ActionLink(SR.Repository_Tree, "Tree", Html.OverRoute(new { path = Model.Sha })));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("        ");

            
            #line 28 "..\..\Views\Repository\Commit.cshtml"
   Write(Model.Parents.Length);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 28 "..\..\Views\Repository\Commit.cshtml"
                         Write(SR.Repository_Parents);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 29 "..\..\Views\Repository\Commit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Repository\Commit.cshtml"
         for (var index = 0; index < Model.Parents.Length; index++)
        {
            if (index > 0)
            {
                
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Repository\Commit.cshtml"
           Write(Html.Raw(" + "));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Repository\Commit.cshtml"
                                
            }
            var parent = Model.Parents[index];
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Repository\Commit.cshtml"
       Write(Html.ActionLink(parent.ToShortSha(), "Commit", Html.OverRoute(new { path = parent })));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Repository\Commit.cshtml"
                                                                                                  
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n\r\n");

            
            #line 41 "..\..\Views\Repository\Commit.cshtml"
Write(Html.Partial("_Diff", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
