#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Views\Repository\Coop.cshtml"
    using NewLife.Serialization;
    
    #line default
    #line hidden
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Coop.cshtml")]
    public partial class _Views_Repository_Coop_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.CollaborationModel>
    {
        public _Views_Repository_Coop_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Repository\Coop.cshtml"
  
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, string.Format(SR.Repository_CollaborationTitle, Model.RepositoryName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>");

            
            #line 8 "..\..\Views\Repository\Coop.cshtml"
Write(string.Format(SR.Repository_CollaborationTitle, Model.RepositoryName));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\r\n");

            
            #line 10 "..\..\Views\Repository\Coop.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n            <span>");

            
            #line 14 "..\..\Views\Repository\Coop.cshtml"
             Write(SR.Shared_Users);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <div");

WriteLiteral(" id=\"choose_user\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n            <span>");

            
            #line 18 "..\..\Views\Repository\Coop.cshtml"
             Write(SR.Shared_Teams);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <div");

WriteLiteral(" id=\"choose_team\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 22 "..\..\Views\Repository\Coop.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var repo = \"");

            
            #line 24 "..\..\Views\Repository\Coop.cshtml"
               Write(Model.RepositoryName);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var chooser_params = [];\r\n        chooser_params.push(\r\n            {" +
"\r\n                data: ");

            
            #line 28 "..\..\Views\Repository\Coop.cshtml"
                 Write(Html.Raw(Model.Users.ToJson()));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                controller: \"Account\",\r\n                container: \"#choose_us" +
"er\",\r\n                add_label: \"");

            
            #line 31 "..\..\Views\Repository\Coop.cshtml"
                       Write(SR.Shared_Add);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                del_label: \"");

            
            #line 32 "..\..\Views\Repository\Coop.cshtml"
                       Write(SR.Shared_Remove);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                add_action: { url: \"");

            
            #line 33 "..\..\Views\Repository\Coop.cshtml"
                               Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"add\" }; } },\r\n" +
"                del_action: { url: \"");

            
            #line 34 "..\..\Views\Repository\Coop.cshtml"
                               Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"del\" }; } },\r\n" +
"                action_array: [\r\n                    {\r\n                        " +
"key: \"AllowRead\",\r\n                        on_label: \"");

            
            #line 38 "..\..\Views\Repository\Coop.cshtml"
                              Write(SR.Repository_ShortAllowRead);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        off_label: \"");

            
            #line 39 "..\..\Views\Repository\Coop.cshtml"
                               Write(SR.Repository_ShortNonAllowRead);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        checked: { url: \"");

            
            #line 40 "..\..\Views\Repository\Coop.cshtml"
                                    Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"read\", value: " +
"true }; } },\r\n                        unchecked: { url: \"");

            
            #line 41 "..\..\Views\Repository\Coop.cshtml"
                                      Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"read\", value: " +
"false }; } },\r\n                    },\r\n                    {\r\n                  " +
"      key: \"AllowWrite\",\r\n                        on_label: \"");

            
            #line 45 "..\..\Views\Repository\Coop.cshtml"
                              Write(SR.Repository_ShortAllowWrite);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        off_label: \"");

            
            #line 46 "..\..\Views\Repository\Coop.cshtml"
                               Write(SR.Repository_ShortNonAllowWrite);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        checked: { url: \"");

            
            #line 47 "..\..\Views\Repository\Coop.cshtml"
                                    Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"write\", value:" +
" true }; } },\r\n                        unchecked: { url: \"");

            
            #line 48 "..\..\Views\Repository\Coop.cshtml"
                                      Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"write\", value:" +
" false }; } },\r\n                    },\r\n                    {\r\n                 " +
"       key: \"IsOwner\",\r\n                        on_label: \"");

            
            #line 52 "..\..\Views\Repository\Coop.cshtml"
                              Write(SR.Repository_ShortIsOwner);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        off_label: \"");

            
            #line 53 "..\..\Views\Repository\Coop.cshtml"
                               Write(SR.Repository_ShortNotOwner);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        checked: { url: \"");

            
            #line 54 "..\..\Views\Repository\Coop.cshtml"
                                    Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"owner\", value:" +
" true }; } },\r\n                        unchecked: { url: \"");

            
            #line 55 "..\..\Views\Repository\Coop.cshtml"
                                      Write(Url.Action("ChooseUser", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, user: item, act: \"owner\", value:" +
" false }; } },\r\n                    },\r\n                ]\r\n            });\r\n\r\n  " +
"      chooser_params.push(\r\n            {\r\n                data: ");

            
            #line 62 "..\..\Views\Repository\Coop.cshtml"
                 Write(Html.Raw(Model.Teams.ToJson()));

            
            #line default
            #line hidden
WriteLiteral(",\r\n                controller: \"Team\",\r\n                container: \"#choose_team\"" +
",\r\n                add_label: \"");

            
            #line 65 "..\..\Views\Repository\Coop.cshtml"
                       Write(SR.Shared_Add);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                del_label: \"");

            
            #line 66 "..\..\Views\Repository\Coop.cshtml"
                       Write(SR.Shared_Remove);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                add_action: { url: \"");

            
            #line 67 "..\..\Views\Repository\Coop.cshtml"
                               Write(Url.Action("ChooseTeam", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, team: item, act: \"add\" }; } },\r\n" +
"                del_action: { url: \"");

            
            #line 68 "..\..\Views\Repository\Coop.cshtml"
                               Write(Url.Action("ChooseTeam", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, team: item, act: \"del\" }; } },\r\n" +
"                action_array: [\r\n                    {\r\n                        " +
"key: \"AllowRead\",\r\n                        on_label: \"");

            
            #line 72 "..\..\Views\Repository\Coop.cshtml"
                              Write(SR.Repository_ShortAllowRead);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        off_label: \"");

            
            #line 73 "..\..\Views\Repository\Coop.cshtml"
                               Write(SR.Repository_ShortNonAllowRead);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        checked: { url: \"");

            
            #line 74 "..\..\Views\Repository\Coop.cshtml"
                                    Write(Url.Action("ChooseTeam", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, team: item, act: \"read\", value: " +
"true }; } },\r\n                        unchecked: { url: \"");

            
            #line 75 "..\..\Views\Repository\Coop.cshtml"
                                      Write(Url.Action("ChooseTeam", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, team: item, act: \"read\", value: " +
"false }; } },\r\n                    },\r\n                    {\r\n                  " +
"      key: \"AllowWrite\",\r\n                        on_label: \"");

            
            #line 79 "..\..\Views\Repository\Coop.cshtml"
                              Write(SR.Repository_ShortAllowWrite);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        off_label: \"");

            
            #line 80 "..\..\Views\Repository\Coop.cshtml"
                               Write(SR.Repository_ShortNonAllowWrite);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        checked: { url: \"");

            
            #line 81 "..\..\Views\Repository\Coop.cshtml"
                                    Write(Url.Action("ChooseTeam", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, team: item, act: \"write\", value:" +
" true }; } },\r\n                        unchecked: { url: \"");

            
            #line 82 "..\..\Views\Repository\Coop.cshtml"
                                      Write(Url.Action("ChooseTeam", "Repository"));

            
            #line default
            #line hidden
WriteLiteral("\", query: function (item) { return { name: repo, team: item, act: \"write\", value:" +
" false }; } },\r\n                    },\r\n                ]\r\n            });\r\n    " +
"</script>\r\n");

            
            #line 87 "..\..\Views\Repository\Coop.cshtml"
}

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Repository\Coop.cshtml"
Write(Html.ActionLink(SR.Shared_Back, "Detail", new { Name = Model.RepositoryName }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
