#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Detail.cshtml")]
    public partial class _Views_Repository_Detail_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.RepositoryModel>
    {
        public _Views_Repository_Detail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\Detail.cshtml"
  
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, string.Format(SR.Repository_DetailTitle, Model.Name));
    var token = GitCandy.Security.Token.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h3>");

            
            #line 8 "..\..\Views\Repository\Detail.cshtml"
Write(string.Format(SR.Repository_DetailTitle, Model.Name));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n");

            
            #line 10 "..\..\Views\Repository\Detail.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n\r\n        <dt>");

            
            #line 14 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Name));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 15 "..\..\Views\Repository\Detail.cshtml"
       Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 17 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.IsPrivate));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 18 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.IsPrivate));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 20 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.AllowAnonymousRead));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 21 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.AllowAnonymousRead));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 23 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.AllowAnonymousWrite));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 24 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.AllowAnonymousWrite));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 26 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.DefaultBranch));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 27 "..\..\Views\Repository\Detail.cshtml"
       Write(Model.DefaultBranch);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 29 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Description));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 30 "..\..\Views\Repository\Detail.cshtml"
       Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 32 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Collaborators));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 33 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.Collaborators));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 35 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Teams));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 36 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.Teams));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 39 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.ActionLink(SR.Repository_Tree, "Tree", new { Model.Name }, new { @class = "btn btn-default pull-left" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n        <dd>\r\n");

            
            #line 42 "..\..\Views\Repository\Detail.cshtml"
        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Repository\Detail.cshtml"
         if (token != null && (Model.CurrentUserIsOwner || token.IsSystemAdministrator))
        {
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.ActionLink(SR.Shared_Edit, "Edit", new { Model.Name }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Repository\Detail.cshtml"
                                                                                                            

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n");

            
            #line 46 "..\..\Views\Repository\Detail.cshtml"
            
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.ActionLink(SR.Repository_Relationship, "Coop", new { Model.Name }, new { @class = "btn btn-info" }));

            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Repository\Detail.cshtml"
                                                                                                                     
        }

            
            #line default
            #line hidden
WriteLiteral("        </dd>\r\n    </dl>\r\n");

            
            #line 50 "..\..\Views\Repository\Detail.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
