//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitCandy.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitCandy.App_GlobalResources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Account with this username already exists..
        /// </summary>
        public static String Account_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Can&apos;t remove yourself.
        /// </summary>
        public static String Account_CantRemoveSelf {
            get {
                return ResourceManager.GetString("Account_CantRemoveSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Change password.
        /// </summary>
        public static String Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Change Password.
        /// </summary>
        public static String Account_ChangePasswordTitle {
            get {
                return ResourceManager.GetString("Account_ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform Password.
        /// </summary>
        public static String Account_ConformPassword {
            get {
                return ResourceManager.GetString("Account_ConformPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Register.
        /// </summary>
        public static String Account_CreateTitle {
            get {
                return ResourceManager.GetString("Account_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Account_CreationUnsuccessfull {
            get {
                return ResourceManager.GetString("Account_CreationUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform Delete User {0}.
        /// </summary>
        public static String Account_DeleteTitle {
            get {
                return ResourceManager.GetString("Account_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to delete the account &quot;{0}&quot;?.
        /// </summary>
        public static String Account_DeletionWords {
            get {
                return ResourceManager.GetString("Account_DeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Description.
        /// </summary>
        public static String Account_Description {
            get {
                return ResourceManager.GetString("Account_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to User {0}.
        /// </summary>
        public static String Account_DetailTitle {
            get {
                return ResourceManager.GetString("Account_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Edit User {0}.
        /// </summary>
        public static String Account_EditTitle {
            get {
                return ResourceManager.GetString("Account_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Email.
        /// </summary>
        public static String Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Account with this email already exists..
        /// </summary>
        public static String Account_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Account_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Forgot username or password.
        /// </summary>
        public static String Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Forgot Password.
        /// </summary>
        public static String Account_ForgotTitle {
            get {
                return ResourceManager.GetString("Account_ForgotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Is system administrator.
        /// </summary>
        public static String Account_IsSystemAdministrator {
            get {
                return ResourceManager.GetString("Account_IsSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to List of Users.
        /// </summary>
        public static String Account_ListTitle {
            get {
                return ResourceManager.GetString("Account_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Username or password error.
        /// </summary>
        public static String Account_LoginFailed {
            get {
                return ResourceManager.GetString("Account_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Log in.
        /// </summary>
        public static String Account_LoginTitle {
            get {
                return ResourceManager.GetString("Account_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to New password.
        /// </summary>
        public static String Account_NewPassword {
            get {
                return ResourceManager.GetString("Account_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Nickname.
        /// </summary>
        public static String Account_Nickname {
            get {
                return ResourceManager.GetString("Account_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Old password.
        /// </summary>
        public static String Account_OldPassword {
            get {
                return ResourceManager.GetString("Account_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Old password error.
        /// </summary>
        public static String Account_OldPasswordError {
            get {
                return ResourceManager.GetString("Account_OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Password.
        /// </summary>
        public static String Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Password error.
        /// </summary>
        public static String Account_PasswordError {
            get {
                return ResourceManager.GetString("Account_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Respositories.
        /// </summary>
        public static String Account_Repositories {
            get {
                return ResourceManager.GetString("Account_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to SSH.
        /// </summary>
        public static String Account_SSH {
            get {
                return ResourceManager.GetString("Account_SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to SSH Key.
        /// </summary>
        public static String Account_SshKeys {
            get {
                return ResourceManager.GetString("Account_SshKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Teams.
        /// </summary>
        public static String Account_Teams {
            get {
                return ResourceManager.GetString("Account_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Account update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Account_UpdateUnsuccessfull {
            get {
                return ResourceManager.GetString("Account_UpdateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Username.
        /// </summary>
        public static String Account_Username {
            get {
                return ResourceManager.GetString("Account_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Username or email.
        /// </summary>
        public static String Account_UsernameOrEmail {
            get {
                return ResourceManager.GetString("Account_UsernameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {0} user(s) found.
        /// </summary>
        public static String Account_UsersFound {
            get {
                return ResourceManager.GetString("Account_UsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to GitCandy&amp;copy; is a [Git](http://git-scm.com/documentation) distributed version control platform based on ASP.NET MVC application, which supports public and private repositories. You can create and collaborate your repository with your team anytime anywhere without any limit.
        ///
        ///Visit a demo on [http://gitcandy.com]()
        ///
        ///Get source and fork me on [http://github.com/Aimeast/GitCandy]()
        ///
        ///---
        ///#### Thanks for (alphabet).
        /// </summary>
        public static String Home_AboutDescription {
            get {
                return ResourceManager.GetString("Home_AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to About.
        /// </summary>
        public static String Home_AboutTitle {
            get {
                return ResourceManager.GetString("Home_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to ahead.
        /// </summary>
        public static String Repository_Ahead {
            get {
                return ResourceManager.GetString("Repository_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Read for anonymous.
        /// </summary>
        public static String Repository_AllowAnonymousRead {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Write for anonymous.
        /// </summary>
        public static String Repository_AllowAnonymousWrite {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repository with this name already exists..
        /// </summary>
        public static String Repository_AlreadyExists {
            get {
                return ResourceManager.GetString("Repository_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to authored at.
        /// </summary>
        public static String Repository_AuthoredAt {
            get {
                return ResourceManager.GetString("Repository_AuthoredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Base branch.
        /// </summary>
        public static String Repository_BaseBranch {
            get {
                return ResourceManager.GetString("Repository_BaseBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to behind.
        /// </summary>
        public static String Repository_Behind {
            get {
                return ResourceManager.GetString("Repository_Behind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to This is a binary file that preview is not supported.
        /// </summary>
        public static String Repository_BinaryFileWrods {
            get {
                return ResourceManager.GetString("Repository_BinaryFileWrods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Blame.
        /// </summary>
        public static String Repository_Blame {
            get {
                return ResourceManager.GetString("Repository_Blame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {2} at {1} · {0}.
        /// </summary>
        public static String Repository_BlameTitle {
            get {
                return ResourceManager.GetString("Repository_BlameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {2} at {1} · {0}.
        /// </summary>
        public static String Repository_BlobTitle {
            get {
                return ResourceManager.GetString("Repository_BlobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to delete the branch &quot;{0}&quot;?.
        /// </summary>
        public static String Repository_BranchDeletionWords {
            get {
                return ResourceManager.GetString("Repository_BranchDeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Branches.
        /// </summary>
        public static String Repository_Branches {
            get {
                return ResourceManager.GetString("Repository_Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Branches · {0}.
        /// </summary>
        public static String Repository_BranchesTitle {
            get {
                return ResourceManager.GetString("Repository_BranchesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Summary: {0} changed files with {1} additions and {2} deletions..
        /// </summary>
        public static String Repository_ChangedSummary {
            get {
                return ResourceManager.GetString("Repository_ChangedSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Collaborations.
        /// </summary>
        public static String Repository_Collaborations {
            get {
                return ResourceManager.GetString("Repository_Collaborations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Collaborations · {0}.
        /// </summary>
        public static String Repository_CollaborationTitle {
            get {
                return ResourceManager.GetString("Repository_CollaborationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Collaborators.
        /// </summary>
        public static String Repository_Collaborators {
            get {
                return ResourceManager.GetString("Repository_Collaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Commits.
        /// </summary>
        public static String Repository_Commits {
            get {
                return ResourceManager.GetString("Repository_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to History for {1} · {0}.
        /// </summary>
        public static String Repository_CommitsTitle {
            get {
                return ResourceManager.GetString("Repository_CommitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to committed at.
        /// </summary>
        public static String Repository_CommittedAt {
            get {
                return ResourceManager.GetString("Repository_CommittedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {2} at {1} · {0}.
        /// </summary>
        public static String Repository_CommitTitle {
            get {
                return ResourceManager.GetString("Repository_CommitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Compare.
        /// </summary>
        public static String Repository_Compare {
            get {
                return ResourceManager.GetString("Repository_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to There is nothing to compare.
        /// </summary>
        public static String Repository_CompareNothing {
            get {
                return ResourceManager.GetString("Repository_CompareNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Compare · {0}.
        /// </summary>
        public static String Repository_CompareTitle {
            get {
                return ResourceManager.GetString("Repository_CompareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Contributors.
        /// </summary>
        public static String Repository_Contributors {
            get {
                return ResourceManager.GetString("Repository_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Contributors · {0}.
        /// </summary>
        public static String Repository_ContributorsTitle {
            get {
                return ResourceManager.GetString("Repository_ContributorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Copied.
        /// </summary>
        public static String Repository_Copied {
            get {
                return ResourceManager.GetString("Repository_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Copy to clipboard.
        /// </summary>
        public static String Repository_CopyToClipboard {
            get {
                return ResourceManager.GetString("Repository_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Create Repository.
        /// </summary>
        public static String Repository_CreateTitle {
            get {
                return ResourceManager.GetString("Repository_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repository creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Repository_CreationUnsuccessfull {
            get {
                return ResourceManager.GetString("Repository_CreationUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Current branch.
        /// </summary>
        public static String Repository_CurrentBranch {
            get {
                return ResourceManager.GetString("Repository_CurrentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Commits in current branch.
        /// </summary>
        public static String Repository_CurrentCommits {
            get {
                return ResourceManager.GetString("Repository_CurrentCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Contributors in current branch.
        /// </summary>
        public static String Repository_CurrentContributors {
            get {
                return ResourceManager.GetString("Repository_CurrentContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Files in current branch.
        /// </summary>
        public static String Repository_CurrentFiles {
            get {
                return ResourceManager.GetString("Repository_CurrentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Source size in current branch.
        /// </summary>
        public static String Repository_CurrentSourceSize {
            get {
                return ResourceManager.GetString("Repository_CurrentSourceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Default branch.
        /// </summary>
        public static String Repository_DefaultBranch {
            get {
                return ResourceManager.GetString("Repository_DefaultBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Commits in default branch.
        /// </summary>
        public static String Repository_DefaultCommits {
            get {
                return ResourceManager.GetString("Repository_DefaultCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Contributors in default branch.
        /// </summary>
        public static String Repository_DefaultContributors {
            get {
                return ResourceManager.GetString("Repository_DefaultContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Files in default branch.
        /// </summary>
        public static String Repository_DefaultFiles {
            get {
                return ResourceManager.GetString("Repository_DefaultFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Source size in default branch.
        /// </summary>
        public static String Repository_DefaultSourceSize {
            get {
                return ResourceManager.GetString("Repository_DefaultSourceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform Delete Repository {0}.
        /// </summary>
        public static String Repository_DeleteTitle {
            get {
                return ResourceManager.GetString("Repository_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to delete the repository &quot;{0}&quot;?.
        /// </summary>
        public static String Repository_DeletionWords {
            get {
                return ResourceManager.GetString("Repository_DeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Description.
        /// </summary>
        public static String Repository_Description {
            get {
                return ResourceManager.GetString("Repository_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repository {0}.
        /// </summary>
        public static String Repository_DetailTitle {
            get {
                return ResourceManager.GetString("Repository_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Edit Repository {0}.
        /// </summary>
        public static String Repository_EditTitle {
            get {
                return ResourceManager.GetString("Repository_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Push a repository with HEAD(master) branch for display here..
        /// </summary>
        public static String Repository_EmptyWords {
            get {
                return ResourceManager.GetString("Repository_EmptyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Added.
        /// </summary>
        public static String Repository_FileAdded {
            get {
                return ResourceManager.GetString("Repository_FileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Copied.
        /// </summary>
        public static String Repository_FileCopied {
            get {
                return ResourceManager.GetString("Repository_FileCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Deleted.
        /// </summary>
        public static String Repository_FileDeleted {
            get {
                return ResourceManager.GetString("Repository_FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Ignored.
        /// </summary>
        public static String Repository_FileIgnored {
            get {
                return ResourceManager.GetString("Repository_FileIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Modified.
        /// </summary>
        public static String Repository_FileModified {
            get {
                return ResourceManager.GetString("Repository_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Renamed.
        /// </summary>
        public static String Repository_FileRenamed {
            get {
                return ResourceManager.GetString("Repository_FileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to TypeChanged.
        /// </summary>
        public static String Repository_FileTypeChanged {
            get {
                return ResourceManager.GetString("Repository_FileTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Unmodified.
        /// </summary>
        public static String Repository_FileUnmodified {
            get {
                return ResourceManager.GetString("Repository_FileUnmodified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Untracked.
        /// </summary>
        public static String Repository_FileUntracked {
            get {
                return ResourceManager.GetString("Repository_FileUntracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Git Url.
        /// </summary>
        public static String Repository_GitUrl {
            get {
                return ResourceManager.GetString("Repository_GitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to The HEAD has not set yet.
        /// </summary>
        public static String Repository_HeadNotSet {
            get {
                return ResourceManager.GetString("Repository_HeadNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to History.
        /// </summary>
        public static String Repository_History {
            get {
                return ResourceManager.GetString("Repository_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to History for ·.
        /// </summary>
        public static String Repository_HistoryFor {
            get {
                return ResourceManager.GetString("Repository_HistoryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Is a private repository.
        /// </summary>
        public static String Repository_IsPrivate {
            get {
                return ResourceManager.GetString("Repository_IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to List of Repositories.
        /// </summary>
        public static String Repository_ListTitle {
            get {
                return ResourceManager.GetString("Repository_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repository name.
        /// </summary>
        public static String Repository_Name {
            get {
                return ResourceManager.GetString("Repository_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Normal view.
        /// </summary>
        public static String Repository_NormalView {
            get {
                return ResourceManager.GetString("Repository_NormalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to No tags found.
        /// </summary>
        public static String Repository_NoTags {
            get {
                return ResourceManager.GetString("Repository_NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Parent(s).
        /// </summary>
        public static String Repository_Parents {
            get {
                return ResourceManager.GetString("Repository_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Popular repositories.
        /// </summary>
        public static String Repository_PopularRepositories {
            get {
                return ResourceManager.GetString("Repository_PopularRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Raw.
        /// </summary>
        public static String Repository_Raw {
            get {
                return ResourceManager.GetString("Repository_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Relationship.
        /// </summary>
        public static String Repository_Relationship {
            get {
                return ResourceManager.GetString("Repository_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repository size.
        /// </summary>
        public static String Repository_RepositorySize {
            get {
                return ResourceManager.GetString("Repository_RepositorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Read.
        /// </summary>
        public static String Repository_ShortAllowRead {
            get {
                return ResourceManager.GetString("Repository_ShortAllowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Write.
        /// </summary>
        public static String Repository_ShortAllowWrite {
            get {
                return ResourceManager.GetString("Repository_ShortAllowWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Owner.
        /// </summary>
        public static String Repository_ShortIsOwner {
            get {
                return ResourceManager.GetString("Repository_ShortIsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to No.
        /// </summary>
        public static String Repository_ShortNonAllowRead {
            get {
                return ResourceManager.GetString("Repository_ShortNonAllowRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to No.
        /// </summary>
        public static String Repository_ShortNonAllowWrite {
            get {
                return ResourceManager.GetString("Repository_ShortNonAllowWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to No.
        /// </summary>
        public static String Repository_ShortNotOwner {
            get {
                return ResourceManager.GetString("Repository_ShortNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Statistics.
        /// </summary>
        public static String Repository_Statistics {
            get {
                return ResourceManager.GetString("Repository_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to delete the tag &quot;{0}&quot;?.
        /// </summary>
        public static String Repository_TagDeletionWords {
            get {
                return ResourceManager.GetString("Repository_TagDeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Tags.
        /// </summary>
        public static String Repository_Tags {
            get {
                return ResourceManager.GetString("Repository_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Tags · {0}.
        /// </summary>
        public static String Repository_TagsTitle {
            get {
                return ResourceManager.GetString("Repository_TagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Teams.
        /// </summary>
        public static String Repository_Teams {
            get {
                return ResourceManager.GetString("Repository_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Tree.
        /// </summary>
        public static String Repository_Tree {
            get {
                return ResourceManager.GetString("Repository_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {2} at {1} · {0}.
        /// </summary>
        public static String Repository_TreeTitle {
            get {
                return ResourceManager.GetString("Repository_TreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repository update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Repository_UpdateUnsuccessfull {
            get {
                return ResourceManager.GetString("Repository_UpdateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Zip.
        /// </summary>
        public static String Repository_Zip {
            get {
                return ResourceManager.GetString("Repository_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Zip with CR (\r).
        /// </summary>
        public static String Repository_ZipCR {
            get {
                return ResourceManager.GetString("Repository_ZipCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Zip with CRLF (\r\n).
        /// </summary>
        public static String Repository_ZipCRLF {
            get {
                return ResourceManager.GetString("Repository_ZipCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Zip with LF (\n).
        /// </summary>
        public static String Repository_ZipLF {
            get {
                return ResourceManager.GetString("Repository_ZipLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Allow register user.
        /// </summary>
        public static String Setting_AllowRegisterUser {
            get {
                return ResourceManager.GetString("Setting_AllowRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Allow repository creation.
        /// </summary>
        public static String Setting_AllowRepositoryCreation {
            get {
                return ResourceManager.GetString("Setting_AllowRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Path of cache directory.
        /// </summary>
        public static String Setting_CachePath {
            get {
                return ResourceManager.GetString("Setting_CachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Settings.
        /// </summary>
        public static String Setting_EditTitle {
            get {
                return ResourceManager.GetString("Setting_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Enable SSH.
        /// </summary>
        public static String Setting_EnableSsh {
            get {
                return ResourceManager.GetString("Setting_EnableSsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Force HTTPS connection.
        /// </summary>
        public static String Setting_ForceSsl {
            get {
                return ResourceManager.GetString("Setting_ForceSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Path of git core.
        /// </summary>
        public static String Setting_GitCorePath {
            get {
                return ResourceManager.GetString("Setting_GitCorePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Is public server.
        /// </summary>
        public static String Setting_IsPublicServer {
            get {
                return ResourceManager.GetString("Setting_IsPublicServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Local skip custom error.
        /// </summary>
        public static String Setting_LocalSkipCustomError {
            get {
                return ResourceManager.GetString("Setting_LocalSkipCustomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Number of commits per page.
        /// </summary>
        public static String Setting_NumberOfCommitsPerPage {
            get {
                return ResourceManager.GetString("Setting_NumberOfCommitsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Number of items per list.
        /// </summary>
        public static String Setting_NumberOfItemsPerList {
            get {
                return ResourceManager.GetString("Setting_NumberOfItemsPerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Number of repository contributors.
        /// </summary>
        public static String Setting_NumberOfRepositoryContributors {
            get {
                return ResourceManager.GetString("Setting_NumberOfRepositoryContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Re-generate ssh key.
        /// </summary>
        public static String Setting_ReGenSsh {
            get {
                return ResourceManager.GetString("Setting_ReGenSsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform to Re-generate ssh key.
        /// </summary>
        public static String Setting_ReGenSshTitle {
            get {
                return ResourceManager.GetString("Setting_ReGenSshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to Re-generate ssh key?.
        /// </summary>
        public static String Setting_ReGenSshWords {
            get {
                return ResourceManager.GetString("Setting_ReGenSshWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Path of repositories.
        /// </summary>
        public static String Setting_RepositoryPath {
            get {
                return ResourceManager.GetString("Setting_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform to restart.
        /// </summary>
        public static String Setting_RestartTitle {
            get {
                return ResourceManager.GetString("Setting_RestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to restart this application?.
        /// </summary>
        public static String Setting_RestartWords {
            get {
                return ResourceManager.GetString("Setting_RestartWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to SSH connection port.
        /// </summary>
        public static String Setting_SshPort {
            get {
                return ResourceManager.GetString("Setting_SshPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to HTTPS connection port.
        /// </summary>
        public static String Setting_SslPort {
            get {
                return ResourceManager.GetString("Setting_SslPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Update settings was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Setting_UpdateSettingsUnsuccessfull {
            get {
                return ResourceManager.GetString("Setting_UpdateSettingsUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to About.
        /// </summary>
        public static String Shared_About {
            get {
                return ResourceManager.GetString("Shared_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Add.
        /// </summary>
        public static String Shared_Add {
            get {
                return ResourceManager.GetString("Shared_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to GitCandy.
        /// </summary>
        public static String Shared_AppTitle {
            get {
                return ResourceManager.GetString("Shared_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Back.
        /// </summary>
        public static String Shared_Back {
            get {
                return ResourceManager.GetString("Shared_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform.
        /// </summary>
        public static String Shared_Conform {
            get {
                return ResourceManager.GetString("Shared_Conform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Create.
        /// </summary>
        public static String Shared_Create {
            get {
                return ResourceManager.GetString("Shared_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Delete.
        /// </summary>
        public static String Shared_Delete {
            get {
                return ResourceManager.GetString("Shared_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Detail.
        /// </summary>
        public static String Shared_Detail {
            get {
                return ResourceManager.GetString("Shared_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Edit.
        /// </summary>
        public static String Shared_Edit {
            get {
                return ResourceManager.GetString("Shared_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Generate.
        /// </summary>
        public static String Shared_Generate {
            get {
                return ResourceManager.GetString("Shared_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Lanuages.
        /// </summary>
        public static String Shared_Lanuages {
            get {
                return ResourceManager.GetString("Shared_Lanuages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Login.
        /// </summary>
        public static String Shared_Login {
            get {
                return ResourceManager.GetString("Shared_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Logout.
        /// </summary>
        public static String Shared_Logout {
            get {
                return ResourceManager.GetString("Shared_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to No.
        /// </summary>
        public static String Shared_No {
            get {
                return ResourceManager.GetString("Shared_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Register.
        /// </summary>
        public static String Shared_Register {
            get {
                return ResourceManager.GetString("Shared_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Remove.
        /// </summary>
        public static String Shared_Remove {
            get {
                return ResourceManager.GetString("Shared_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repositories.
        /// </summary>
        public static String Shared_Repositories {
            get {
                return ResourceManager.GetString("Shared_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Reset.
        /// </summary>
        public static String Shared_Reset {
            get {
                return ResourceManager.GetString("Shared_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Restart.
        /// </summary>
        public static String Shared_Restart {
            get {
                return ResourceManager.GetString("Shared_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Save.
        /// </summary>
        public static String Shared_Save {
            get {
                return ResourceManager.GetString("Shared_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Search.
        /// </summary>
        public static String Shared_Search {
            get {
                return ResourceManager.GetString("Shared_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Settings.
        /// </summary>
        public static String Shared_Settings {
            get {
                return ResourceManager.GetString("Shared_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Something wrong.
        /// </summary>
        public static String Shared_SomethingWrong {
            get {
                return ResourceManager.GetString("Shared_SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Teams.
        /// </summary>
        public static String Shared_Teams {
            get {
                return ResourceManager.GetString("Shared_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {0} - GitCandy.
        /// </summary>
        public static String Shared_TitleFormat {
            get {
                return ResourceManager.GetString("Shared_TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Users.
        /// </summary>
        public static String Shared_Users {
            get {
                return ResourceManager.GetString("Shared_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Yes.
        /// </summary>
        public static String Shared_Yes {
            get {
                return ResourceManager.GetString("Shared_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Team with this name already exists..
        /// </summary>
        public static String Team_AlreadyExists {
            get {
                return ResourceManager.GetString("Team_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Choose Users for Team {0}.
        /// </summary>
        public static String Team_ChooseUserTitle {
            get {
                return ResourceManager.GetString("Team_ChooseUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Create Team.
        /// </summary>
        public static String Team_CreationTitle {
            get {
                return ResourceManager.GetString("Team_CreationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Team creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Team_CreationUnsuccessfull {
            get {
                return ResourceManager.GetString("Team_CreationUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Conform Delete Team {0}.
        /// </summary>
        public static String Team_DeleteTitle {
            get {
                return ResourceManager.GetString("Team_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Do you conform to delete the team &quot;{0}&quot;?.
        /// </summary>
        public static String Team_DeletionWords {
            get {
                return ResourceManager.GetString("Team_DeletionWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Team description.
        /// </summary>
        public static String Team_Description {
            get {
                return ResourceManager.GetString("Team_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Team {0}.
        /// </summary>
        public static String Team_DetailTitle {
            get {
                return ResourceManager.GetString("Team_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Edit Team {0}.
        /// </summary>
        public static String Team_EditTitle {
            get {
                return ResourceManager.GetString("Team_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to List of Teams.
        /// </summary>
        public static String Team_ListTitle {
            get {
                return ResourceManager.GetString("Team_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Members.
        /// </summary>
        public static String Team_Members {
            get {
                return ResourceManager.GetString("Team_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Team name.
        /// </summary>
        public static String Team_Name {
            get {
                return ResourceManager.GetString("Team_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Repositories.
        /// </summary>
        public static String Team_Repositories {
            get {
                return ResourceManager.GetString("Team_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Admin.
        /// </summary>
        public static String Team_ShortAdministrator {
            get {
                return ResourceManager.GetString("Team_ShortAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to No.
        /// </summary>
        public static String Team_ShortNonAdministrator {
            get {
                return ResourceManager.GetString("Team_ShortNonAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {0} team(s) found.
        /// </summary>
        public static String Team_TeamsFound {
            get {
                return ResourceManager.GetString("Team_TeamsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to Team update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static String Team_UpdateUnsuccessfull {
            get {
                return ResourceManager.GetString("Team_UpdateUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; and &quot;{1}&quot; must have the same value.
        /// </summary>
        public static String Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; is not a valid email address.
        /// </summary>
        public static String Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; is not a valid &quot;{1}&quot; file path.
        /// </summary>
        public static String Validation_Filepath {
            get {
                return ResourceManager.GetString("Validation_Filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; not a valid.
        /// </summary>
        public static String Validation_Name {
            get {
                return ResourceManager.GetString("Validation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to {0} can only be between {1} and {2}.
        /// </summary>
        public static String Validation_NumberRange {
            get {
                return ResourceManager.GetString("Validation_NumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; is mandatory.
        /// </summary>
        public static String Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; should be smaller than {1} chars.
        /// </summary>
        public static String Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to &quot;{0}&quot; should be smaller than {1} chars and large then {2} chars.
        /// </summary>
        public static String Validation_StringLengthRange {
            get {
                return ResourceManager.GetString("Validation_StringLengthRange", resourceCulture);
            }
        }
    }
}
