#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using GitCandy.Web;
    using GitCandy.Web.App_GlobalResources;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/_GitUrlButton.cshtml")]
    public partial class _Views_Repository__GitUrlButton_cshtml : System.Web.Mvc.WebViewPage<GitUrl[]>
    {
        public _Views_Repository__GitUrlButton_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\_GitUrlButton.cshtml"
  
    var first = Model.First();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"input-group url-path\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Repository\_GitUrlButton.cshtml"
                                                                              Write(first.Type);

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span></button>\r\n            <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Repository\_GitUrlButton.cshtml"
                
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Repository\_GitUrlButton.cshtml"
                 foreach (var item in Model)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" data-giturl=\"");

            
            #line 14 "..\..\Views\Repository\_GitUrlButton.cshtml"
                                Write(item.Url);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Repository\_GitUrlButton.cshtml"
                                                       Write(item.Type);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 15 "..\..\Views\Repository\_GitUrlButton.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n        </div>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" readonly");

WriteAttribute("value", Tuple.Create(" value=\"", 593), Tuple.Create("\"", 611)
            
            #line 18 "..\..\Views\Repository\_GitUrlButton.cshtml"
, Tuple.Create(Tuple.Create("", 601), Tuple.Create<System.Object, System.Int32>(first.Url
            
            #line default
            #line hidden
, 601), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default copy-clip tip\"");

WriteAttribute("aria-label", Tuple.Create(" aria-label=\"", 711), Tuple.Create("\"", 754)
            
            #line 20 "..\..\Views\Repository\_GitUrlButton.cshtml"
, Tuple.Create(Tuple.Create("", 724), Tuple.Create<System.Object, System.Int32>(SR.Repository_CopyToClipboard
            
            #line default
            #line hidden
, 724), false)
);

WriteLiteral(" data-tips=\"");

            
            #line 20 "..\..\Views\Repository\_GitUrlButton.cshtml"
                                                                                                            Write(SR.Repository_CopyToClipboard);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-copied=\"");

            
            #line 20 "..\..\Views\Repository\_GitUrlButton.cshtml"
                                                                                                                                                         Write(SR.Repository_Copied);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-copy\"");

WriteLiteral("></i></button>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
