#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using GitCandy.Web;
    using GitCandy.Web.App_GlobalResources;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Blame.cshtml")]
    public partial class _Views_Repository_Blame_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.BlameModel>
    {
        public _Views_Repository_Blame_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\Blame.cshtml"
  
    ViewBag.Title = String.Format(SR.Shared_TitleFormat, String.Format(SR.Repository_BlameTitle, Model.Name, Model.ReferenceName ?? Model.Sha.ToShortSha(), Model.Path));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>");

            
            #line 7 "..\..\Views\Repository\Blame.cshtml"
Write(Html.Link(Model));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\r\n");

            
            #line 9 "..\..\Views\Repository\Blame.cshtml"
Write(Html.Partial("_PathBar", Model.PathBar));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Repository\Blame.cshtml"
Write(Html.Partial("_BranchSelector", Model.BranchSelector));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Repository\Blame.cshtml"
       Write(Html.ActionLink(SR.Repository_History, "Commits", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Sha) + "/" + Model.Path }), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Repository\Blame.cshtml"
       Write(Html.ActionLink(SR.Repository_NormalView, "Blob", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Sha) + "/" + Model.Path }), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\Repository\Blame.cshtml"
       Write(Html.ActionLink(SR.Repository_Raw, "Raw", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Sha) + "/" + Model.Path }), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Repository\Blame.cshtml"
   Write(Model.SizeString);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(" data-brush=\"");

            
            #line 23 "..\..\Views\Repository\Blame.cshtml"
                                           Write(Model.Brush);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <tbody>\r\n");

            
            #line 25 "..\..\Views\Repository\Blame.cshtml"
        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Repository\Blame.cshtml"
         foreach (var hunk in Model.Hunks)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" class=\"blame-info\"");

WriteLiteral(">\r\n                    <div>\r\n                        <span>");

            
            #line 30 "..\..\Views\Repository\Blame.cshtml"
                         Write(Html.ActionLink(hunk.Sha.ToShortSha(), "Commit", Html.OverRoute(new { path = hunk.Sha + "/" + Model.Path })));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <span>");

            
            #line 31 "..\..\Views\Repository\Blame.cshtml"
                         Write(Html.ActionLink("»", "Blame", Html.OverRoute(new { path = hunk.Sha + "/" + Model.Path })));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 1570), Tuple.Create("\"", 1595)
            
            #line 32 "..\..\Views\Repository\Blame.cshtml"
, Tuple.Create(Tuple.Create("", 1578), Tuple.Create<System.Object, System.Int32>(hunk.AuthorEmail
            
            #line default
            #line hidden
, 1578), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\Repository\Blame.cshtml"
                                                     Write(hunk.Author);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                    </div>\r\n                    <div>\r\n               " +
"         <span");

WriteAttribute("title", Tuple.Create(" title=\"", 1704), Tuple.Create("\"", 1728)
            
            #line 35 "..\..\Views\Repository\Blame.cshtml"
, Tuple.Create(Tuple.Create("", 1712), Tuple.Create<System.Object, System.Int32>(hunk.AuthorDate
            
            #line default
            #line hidden
, 1712), false)
);

WriteLiteral(">");

            
            #line 35 "..\..\Views\Repository\Blame.cshtml"
                                                  Write(hunk.AuthorDate.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <span");

WriteAttribute("title", Tuple.Create(" title=\"", 1813), Tuple.Create("\"", 1839)
            
            #line 36 "..\..\Views\Repository\Blame.cshtml"
, Tuple.Create(Tuple.Create("", 1821), Tuple.Create<System.Object, System.Int32>(hunk.MessageShort
            
            #line default
            #line hidden
, 1821), false)
);

WriteLiteral(">");

            
            #line 36 "..\..\Views\Repository\Blame.cshtml"
                                                    Write(hunk.MessageShort.ShortString(33));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </td>\r\n                <td><" +
"pre");

WriteLiteral(" class=\"blame-code\"");

WriteLiteral("><code");

WriteLiteral(" class=\"language no-highlight blame-code\"");

WriteLiteral(">");

            
            #line 39 "..\..\Views\Repository\Blame.cshtml"
                                                                                      Write(hunk.Code);

            
            #line default
            #line hidden
WriteLiteral("</code></pre></td>\r\n            </tr>\r\n");

            
            #line 41 "..\..\Views\Repository\Blame.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
