#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.App_GlobalResources;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Compare.cshtml")]
    public partial class _Views_Repository_Compare_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.CompareModel>
    {
        public _Views_Repository_Compare_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\Compare.cshtml"
  
    ViewBag.Title = String.Format(SR.Shared_TitleFormat, String.Format(SR.Repository_CompareTitle, Model.RepositoryName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>");

            
            #line 7 "..\..\Views\Repository\Compare.cshtml"
Write(Html.ActionLink(Model.RepositoryName, "Tree", Html.OverRoute(new { path = "" })));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-3 branch-from\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Repository\Compare.cshtml"
   Write(Html.Partial("_BranchSelector", Model.BaseBranchSelector));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-3 branch-to\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Repository\Compare.cshtml"
   Write(Html.Partial("_BranchSelector", Model.CompareBranchSelector));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"branch-compare btn btn-primary\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Repository\Compare.cshtml"
                                                  Write(SR.Repository_Compare);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 21 "..\..\Views\Repository\Compare.cshtml"
 if (Model.Walks == null || Model.Walks.Length == 0)
{
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Repository\Compare.cshtml"
Write(SR.Repository_CompareNothing);

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Repository\Compare.cshtml"
                                 
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"border-area table-responsive\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table table-hover\"");

WriteLiteral(">\r\n            <tbody>\r\n");

            
            #line 30 "..\..\Views\Repository\Compare.cshtml"
                
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Repository\Compare.cshtml"
                 foreach (var commit in Model.Walks)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td><span");

WriteAttribute("title", Tuple.Create(" title=\"", 1012), Tuple.Create("\"", 1037)
            
            #line 33 "..\..\Views\Repository\Compare.cshtml"
, Tuple.Create(Tuple.Create("", 1020), Tuple.Create<System.Object, System.Int32>(commit.Committer
            
            #line default
            #line hidden
, 1020), false)
);

WriteLiteral(">");

            
            #line 33 "..\..\Views\Repository\Compare.cshtml"
                                                       Write(commit.Committer.Name.ShortString(20));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                        <td><span");

WriteAttribute("title", Tuple.Create(" title=\"", 1124), Tuple.Create("\"", 1154)
            
            #line 34 "..\..\Views\Repository\Compare.cshtml"
, Tuple.Create(Tuple.Create("", 1132), Tuple.Create<System.Object, System.Int32>(commit.Committer.When
            
            #line default
            #line hidden
, 1132), false)
);

WriteLiteral(">");

            
            #line 34 "..\..\Views\Repository\Compare.cshtml"
                                                            Write(commit.Committer.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n                        <td>");

            
            #line 35 "..\..\Views\Repository\Compare.cshtml"
                       Write(Html.ActionLink(commit.CommitMessageShort.ShortString(80), "Commit", Html.OverRoute(new { path = commit.Sha })));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");

            
            #line 37 "..\..\Views\Repository\Compare.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n");

            
            #line 41 "..\..\Views\Repository\Compare.cshtml"

    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Repository\Compare.cshtml"
Write(Html.Partial("_Diff", Model.CompareResult));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Repository\Compare.cshtml"
                                               
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
