#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.Base;
    using GitCandy.Configuration;
    
    #line 3 "..\..\Views\Repository\Detail.cshtml"
    using GitCandy.Extensions;
    
    #line default
    #line hidden
    using GitCandy.Models;
    using GitCandy.Web;
    using GitCandy.Web.App_GlobalResources;
    using NewLife;
    using NewLife.Cube;
    
    #line 2 "..\..\Views\Repository\Detail.cshtml"
    using NewLife.Model;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Detail.cshtml")]
    public partial class _Views_Repository_Detail_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.RepositoryModel>
    {
        public _Views_Repository_Detail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Repository\Detail.cshtml"
  
    ViewBag.Title = String.Format(SR.Shared_TitleFormat, String.Format(SR.Repository_DetailTitle, Model.Name));
    var token = User.Identity as IManageUser;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h3>");

            
            #line 9 "..\..\Views\Repository\Detail.cshtml"
Write(String.Format(SR.Repository_DetailTitle, Model.Name));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n");

            
            #line 11 "..\..\Views\Repository\Detail.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n\r\n        <dt>");

            
            #line 15 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Name));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 16 "..\..\Views\Repository\Detail.cshtml"
       Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 18 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.IsPrivate));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 19 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.IsPrivate));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 21 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.AllowAnonymousRead));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 22 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.AllowAnonymousRead));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 24 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.AllowAnonymousWrite));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 25 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.AllowAnonymousWrite));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 27 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.DefaultBranch));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 28 "..\..\Views\Repository\Detail.cshtml"
       Write(Model.DefaultBranch);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 30 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Description));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 31 "..\..\Views\Repository\Detail.cshtml"
       Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 33 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Collaborators));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 34 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.Collaborators));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 36 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Teams));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 37 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.Teams));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 39 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Views));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 40 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.Views));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>");

            
            #line 42 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayNameFor(s => s.Downloads));

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n        <dd>");

            
            #line 43 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.DisplayFor(s => s.Downloads));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Views\Repository\Detail.cshtml"
       Write(Html.ActionLink(SR.Repository_Tree, "Tree", new { Model.Name }, new { @class = "btn btn-default pull-left" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n        <dd>\r\n");

            
            #line 49 "..\..\Views\Repository\Detail.cshtml"
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Repository\Detail.cshtml"
             if (token != null && (Model.CurrentUserIsOwner || token.IsAdmin()))
            {
                
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Repository\Detail.cshtml"
           Write(Html.ActionLink(SR.Shared_Edit, "Edit", new { Model.Name }, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Repository\Detail.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n");

            
            #line 53 "..\..\Views\Repository\Detail.cshtml"
                
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Repository\Detail.cshtml"
           Write(Html.ActionLink(SR.Repository_Relationship, "Coop", new { Model.Name }, new { @class = "btn btn-info" }));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Repository\Detail.cshtml"
                                                                                                                         
            }

            
            #line default
            #line hidden
WriteLiteral("        </dd>\r\n    </dl>\r\n");

            
            #line 57 "..\..\Views\Repository\Detail.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
