#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using GitCandy.Web;
    using GitCandy.Web.App_GlobalResources;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Index.cshtml")]
    public partial class _Views_Repository_Index_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.RepositoryListModel>
    {
        public _Views_Repository_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Repository\Index.cshtml"
  
    //ViewBag.Title = String.Format(SR.Shared_TitleFormat, SR.Repository_ListTitle);
    ViewBag.Title = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table border-area\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Repository\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Repository\Index.cshtml"
             foreach (var repo in Model.Collaborations)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <div><h3>" +
"<a");

WriteAttribute("href", Tuple.Create(" href=\"", 409), Tuple.Create("\"", 440)
, Tuple.Create(Tuple.Create("", 416), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 416), false)
            
            #line 14 "..\..\Views\Repository\Index.cshtml"
, Tuple.Create(Tuple.Create("", 418), Tuple.Create<System.Object, System.Int32>(repo.Owner
            
            #line default
            #line hidden
, 418), false)
, Tuple.Create(Tuple.Create("", 429), Tuple.Create("/", 429), true)
            
            #line 14 "..\..\Views\Repository\Index.cshtml"
, Tuple.Create(Tuple.Create("", 430), Tuple.Create<System.Object, System.Int32>(repo.Name
            
            #line default
            #line hidden
, 430), false)
);

WriteLiteral(">");

            
            #line 14 "..\..\Views\Repository\Index.cshtml"
                                                               Write(repo.Owner);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 14 "..\..\Views\Repository\Index.cshtml"
                                                                           Write(repo.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></h3></div>\r\n                        <div>");

            
            #line 15 "..\..\Views\Repository\Index.cshtml"
                        Write(repo.Description);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div");

WriteLiteral(" style=\"margin-top: 10px;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" title=\"浏览\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-heart\"");

WriteLiteral(" style=\"color: deeppink;\"");

WriteLiteral("></i> ");

            
            #line 18 "..\..\Views\Repository\Index.cshtml"
                                                                                                               Write(repo.Views);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span");

WriteLiteral(" title=\"提交\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-star\"");

WriteLiteral(" style=\"color: mediumpurple;\"");

WriteLiteral("></i> ");

            
            #line 19 "..\..\Views\Repository\Index.cshtml"
                                                                                                                  Write(repo.Commits);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span");

WriteLiteral(" title=\"参与\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral(" style=\"color: forestgreen;\"");

WriteLiteral("></i> ");

            
            #line 20 "..\..\Views\Repository\Index.cshtml"
                                                                                                                 Write(repo.Contributors);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6 text-right\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Repository\Index.cshtml"
                                                        Write(repo.LastCommit.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </div>\r\n                    </td>\r\n              " +
"  </tr>\r\n");

            
            #line 26 "..\..\Views\Repository\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table border-area\"");

WriteLiteral(">\r\n            <thead>");

            
            #line 32 "..\..\Views\Repository\Index.cshtml"
              Write(SR.Repository_PopularRepositories);

            
            #line default
            #line hidden
WriteLiteral("</thead>\r\n");

            
            #line 33 "..\..\Views\Repository\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Repository\Index.cshtml"
             foreach (var repo in Model.Repositories)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <div><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1614), Tuple.Create("\"", 1645)
, Tuple.Create(Tuple.Create("", 1621), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1621), false)
            
            #line 37 "..\..\Views\Repository\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1623), Tuple.Create<System.Object, System.Int32>(repo.Owner
            
            #line default
            #line hidden
, 1623), false)
, Tuple.Create(Tuple.Create("", 1634), Tuple.Create("/", 1634), true)
            
            #line 37 "..\..\Views\Repository\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1635), Tuple.Create<System.Object, System.Int32>(repo.Name
            
            #line default
            #line hidden
, 1635), false)
);

WriteLiteral(">");

            
            #line 37 "..\..\Views\Repository\Index.cshtml"
                                                           Write(repo.Owner);

            
            #line default
            #line hidden
WriteLiteral("/");

            
            #line 37 "..\..\Views\Repository\Index.cshtml"
                                                                       Write(repo.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></div>\r\n                        <div>");

            
            #line 38 "..\..\Views\Repository\Index.cshtml"
                        Write(repo.Description);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" title=\"浏览\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-heart\"");

WriteLiteral(" style=\"color: deeppink;\"");

WriteLiteral("></i> ");

            
            #line 41 "..\..\Views\Repository\Index.cshtml"
                                                                                                               Write(repo.Views);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span");

WriteLiteral(" title=\"提交\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-star\"");

WriteLiteral(" style=\"color: mediumpurple;\"");

WriteLiteral("></i> ");

            
            #line 42 "..\..\Views\Repository\Index.cshtml"
                                                                                                                  Write(repo.Commits);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <span");

WriteLiteral(" title=\"参与\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral(" style=\"color: forestgreen;\"");

WriteLiteral("></i> ");

            
            #line 43 "..\..\Views\Repository\Index.cshtml"
                                                                                                                 Write(repo.Contributors);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6 text-right\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Repository\Index.cshtml"
                                                        Write(repo.LastCommit.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </div>\r\n                    </td>\r\n              " +
"  </tr>\r\n");

            
            #line 49 "..\..\Views\Repository\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
