#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GitCandy;
    using GitCandy.Base;
    using GitCandy.Configuration;
    using GitCandy.Extensions;
    using GitCandy.Models;
    using GitCandy.Web;
    using GitCandy.Web.App_GlobalResources;
    
    #line 2 "..\..\Views\Repository\Tree.cshtml"
    using LibGit2Sharp;
    
    #line default
    #line hidden
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Serialization;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Repository/Tree.cshtml")]
    public partial class _Views_Repository_Tree_cshtml : System.Web.Mvc.WebViewPage<GitCandy.Models.TreeModel>
    {
        public _Views_Repository_Tree_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Repository\Tree.cshtml"
  
    ViewBag.Title = String.Format(SR.Shared_TitleFormat, String.Format(SR.Repository_TreeTitle, Model.Name, Model.ReferenceName ?? Model.Commit.Sha.ToShortSha(), Model.Path));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h3>");

            
            #line 8 "..\..\Views\Repository\Tree.cshtml"
Write(Html.Link(Model));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n");

            
            #line 10 "..\..\Views\Repository\Tree.cshtml"
 if (Model.Entries == null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Repository\Tree.cshtml"
   Write(Html.ActionLink(SR.Shared_Detail, "Detail", Html.OverRoute(), new { @class = "btn btn-default pull-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Repository\Tree.cshtml"
   Write(Html.Partial("_GitUrlButton", Model.GitUrls));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Repository\Tree.cshtml"
                             Write(SR.Repository_EmptyWords);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 17 "..\..\Views\Repository\Tree.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

            
            #line 21 "..\..\Views\Repository\Tree.cshtml"
        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Repository\Tree.cshtml"
         if (Model.IsRoot)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h5>");

            
            #line 23 "..\..\Views\Repository\Tree.cshtml"
           Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</h5>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"border-area\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav nav-justified\"");

WriteLiteral(">\r\n                    <li>");

            
            #line 26 "..\..\Views\Repository\Tree.cshtml"
                   Write(Html.ActionLink(Model.Scope.Commits + " " + SR.Repository_Commits, "Commits"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");

            
            #line 27 "..\..\Views\Repository\Tree.cshtml"
                   Write(Html.ActionLink(Model.Scope.Branches + " " + SR.Repository_Branches, "Branches"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");

            
            #line 28 "..\..\Views\Repository\Tree.cshtml"
                   Write(Html.ActionLink(Model.Scope.Tags + " " + SR.Repository_Tags, "Tags"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");

            
            #line 29 "..\..\Views\Repository\Tree.cshtml"
                   Write(Html.ActionLink(Model.Scope.Contributors + " " + SR.Repository_Contributors, "Contributors"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                </ul>\r\n            </div>\r\n");

            
            #line 32 "..\..\Views\Repository\Tree.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div>\r\n");

            
            #line 35 "..\..\Views\Repository\Tree.cshtml"
            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Repository\Tree.cshtml"
             if (Model.IsRoot)
            {
                
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Repository\Tree.cshtml"
           Write(Html.ActionLink(SR.Shared_Detail, "Detail", Html.OverRoute(), new { @class = "btn btn-default pull-right" }));

            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Repository\Tree.cshtml"
                                                                                                                             
                
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Repository\Tree.cshtml"
           Write(Html.Partial("_BranchSelector", Model.BranchSelector));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Repository\Tree.cshtml"
                                                                      
                
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Repository\Tree.cshtml"
           Write(Html.Partial("_ZipButton", Model.ReferenceName ?? Model.Commit.Sha));

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Repository\Tree.cshtml"
                                                                                    

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1626), Tuple.Create("\"", 1690)
            
            #line 40 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 1633), Tuple.Create<System.Object, System.Int32>(Url.Action("Compare", Html.OverRoute(new { path = "" }))
            
            #line default
            #line hidden
, 1633), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-retweet\"");

WriteLiteral("></span>");

            
            #line 40 "..\..\Views\Repository\Tree.cshtml"
                                                                                                                                                        Write(SR.Repository_Compare);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 41 "..\..\Views\Repository\Tree.cshtml"
                
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Repository\Tree.cshtml"
           Write(Html.Partial("_GitUrlButton", Model.GitUrls));

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Repository\Tree.cshtml"
                                                             
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Repository\Tree.cshtml"
           Write(Html.Partial("_BranchSelector", Model.BranchSelector));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Repository\Tree.cshtml"
                                                                      

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Views\Repository\Tree.cshtml"
               Write(Html.ActionLink(SR.Repository_History, "Commits", Html.OverRoute(new { path = (Model.ReferenceName ?? Model.Commit.Sha) + "/" + Model.Path }), new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 49 "..\..\Views\Repository\Tree.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Views\Repository\Tree.cshtml"
   Write(Html.Partial("_PathBar", Model.PathBar));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"border-area table-responsive\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table table-hover table-striped\"");

WriteLiteral(">\r\n                <caption>\r\n                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                        <div");

WriteAttribute("title", Tuple.Create(" title=\"", 2535), Tuple.Create("\"", 2575)
            
            #line 56 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 2543), Tuple.Create<System.Object, System.Int32>(Model.Commit.CommitMessageShort
            
            #line default
            #line hidden
, 2543), false)
);

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Repository\Tree.cshtml"
                                                                                   Write(Html.ActionLink(Model.Commit.CommitMessageShort.ShortString(80), "Commit", Html.OverRoute(new { path = Model.Commit.Sha })));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                        <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 2830), Tuple.Create("\"", 2858)
            
            #line 59 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 2838), Tuple.Create<System.Object, System.Int32>(Model.Commit.Author
            
            #line default
            #line hidden
, 2838), false)
);

WriteLiteral(">");

            
            #line 59 "..\..\Views\Repository\Tree.cshtml"
                                                        Write(Html.Link(Model.Commit.Author));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                        <span>");

            
            #line 60 "..\..\Views\Repository\Tree.cshtml"
                         Write(SR.Repository_AuthoredAt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <span");

WriteAttribute("title", Tuple.Create(" title=\"", 2995), Tuple.Create("\"", 3028)
            
            #line 61 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 3003), Tuple.Create<System.Object, System.Int32>(Model.Commit.Author.When
            
            #line default
            #line hidden
, 3003), false)
);

WriteLiteral(">");

            
            #line 61 "..\..\Views\Repository\Tree.cshtml"
                                                           Write(Model.Commit.Author.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 62 "..\..\Views\Repository\Tree.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Repository\Tree.cshtml"
                         if (Model.Commit.Author != Model.Commit.Committer)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <strong");

WriteAttribute("title", Tuple.Create(" title=\"", 3232), Tuple.Create("\"", 3263)
            
            #line 64 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 3240), Tuple.Create<System.Object, System.Int32>(Model.Commit.Committer
            
            #line default
            #line hidden
, 3240), false)
);

WriteLiteral(">");

            
            #line 64 "..\..\Views\Repository\Tree.cshtml"
                                                               Write(Model.Commit.Committer.Name);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n");

WriteLiteral("                            <span>");

            
            #line 65 "..\..\Views\Repository\Tree.cshtml"
                             Write(SR.Repository_CommittedAt);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

WriteLiteral("                            <span");

WriteAttribute("title", Tuple.Create(" title=\"", 3406), Tuple.Create("\"", 3442)
            
            #line 66 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 3414), Tuple.Create<System.Object, System.Int32>(Model.Commit.Committer.When
            
            #line default
            #line hidden
, 3414), false)
);

WriteLiteral(">");

            
            #line 66 "..\..\Views\Repository\Tree.cshtml"
                                                                  Write(Model.Commit.Committer.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 67 "..\..\Views\Repository\Tree.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\Repository\Tree.cshtml"
                                           Write(Model.Commit.Sha.ToShortSha());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                </caption>\r\n                <" +
"tbody>\r\n");

            
            #line 72 "..\..\Views\Repository\Tree.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Repository\Tree.cshtml"
                     foreach (var entry in Model.Entries)
                    {
                        var commit = entry.Commit ?? new CommitModel();
                        var author = commit.Author;

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>\r\n                 " +
"               <span");

WriteAttribute("title", Tuple.Create(" title=\"", 4013), Tuple.Create("\"", 4032)
            
            #line 78 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 4021), Tuple.Create<System.Object, System.Int32>(entry.Name
            
            #line default
            #line hidden
, 4021), false)
);

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Views\Repository\Tree.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Repository\Tree.cshtml"
                                     if (entry.EntryType == TreeEntryTargetType.Tree)
                                    {
            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"glyphicon glyphicon-folder-close\"");

WriteLiteral("></span> ");

            
            #line 80 "..\..\Views\Repository\Tree.cshtml"
                                                                                            }
                                    else if (entry.EntryType == TreeEntryTargetType.Blob)
                                    {
            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"glyphicon glyphicon-file\"");

WriteLiteral("></span> ");

            
            #line 82 "..\..\Views\Repository\Tree.cshtml"
                                                                                     }
                                    else if (entry.EntryType == TreeEntryTargetType.GitLink)
                                    {
            
            #line default
            #line hidden
WriteLiteral(" <i");

WriteLiteral(" class=\"glyphicon glyphicon-bookmark\"");

WriteLiteral("></i> ");

            
            #line 84 "..\..\Views\Repository\Tree.cshtml"
                                                                                   }
                                    else
                                    {
            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"glyphicon glyphicon-leaf\"");

WriteLiteral("></span>");

            
            #line 86 "..\..\Views\Repository\Tree.cshtml"
                                                                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

            
            #line 87 "..\..\Views\Repository\Tree.cshtml"
                                     if (entry.EntryType == TreeEntryTargetType.GitLink)
                                    {
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Repository\Tree.cshtml"
                                Write(entry.Name.ShortString(25));

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Repository\Tree.cshtml"
                                                                 }
                                else
                                {
            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4938), Tuple.Create("\"", 4992)
            
            #line 90 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 4945), Tuple.Create<System.Object, System.Int32>(Model.GetUrl(entry.EntryType + "", entry.Path)
            
            #line default
            #line hidden
, 4945), false)
);

WriteLiteral(">");

            
            #line 90 "..\..\Views\Repository\Tree.cshtml"
                                                                                       Write(entry.Name.ShortString(25));

            
            #line default
            #line hidden
WriteLiteral("</a>");

            
            #line 90 "..\..\Views\Repository\Tree.cshtml"
                                                                                                                           }

            
            #line default
            #line hidden
WriteLiteral("                                </span>\r\n                            </td>\r\n     " +
"                       <td><span");

WriteAttribute("title", Tuple.Create(" title=\"", 5141), Tuple.Create("\"", 5175)
            
            #line 93 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 5149), Tuple.Create<System.Object, System.Int32>(commit.CommitMessageShort
            
            #line default
            #line hidden
, 5149), false)
);

WriteLiteral(">");

            
            #line 93 "..\..\Views\Repository\Tree.cshtml"
                                                                     Write(commit.Sha == null ? Html.Raw(commit.CommitMessageShort) : Html.ActionLink(commit.CommitMessageShort.ShortString(70), "Commit", Html.OverRoute(new { path = commit.Sha })));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n");

            
            #line 94 "..\..\Views\Repository\Tree.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 94 "..\..\Views\Repository\Tree.cshtml"
                             if (author != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 5480), Tuple.Create("\"", 5495)
            
            #line 96 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 5488), Tuple.Create<System.Object, System.Int32>(author
            
            #line default
            #line hidden
, 5488), false)
);

WriteLiteral(">");

            
            #line 96 "..\..\Views\Repository\Tree.cshtml"
                                               Write(author.Name.ShortString(20));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

WriteLiteral("                                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 5567), Tuple.Create("\"", 5587)
            
            #line 97 "..\..\Views\Repository\Tree.cshtml"
, Tuple.Create(Tuple.Create("", 5575), Tuple.Create<System.Object, System.Int32>(author.When
            
            #line default
            #line hidden
, 5575), false)
);

WriteLiteral(">");

            
            #line 97 "..\..\Views\Repository\Tree.cshtml"
                                                    Write(author.When.LocalDateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 98 "..\..\Views\Repository\Tree.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <td></td>\r\n");

WriteLiteral("                                <td></td>\r\n");

            
            #line 103 "..\..\Views\Repository\Tree.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tr>\r\n");

            
            #line 105 "..\..\Views\Repository\Tree.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n        </div>\r\n");

            
            #line 109 "..\..\Views\Repository\Tree.cshtml"
        
            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\Repository\Tree.cshtml"
         if (Model.Readme != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"border-area\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                    <caption>\r\n                        <div");

WriteLiteral(" class=\"pull-left keep-space\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-list-alt\"");

WriteLiteral("></i> ");

            
            #line 114 "..\..\Views\Repository\Tree.cshtml"
                                                                                                  Write(Model.Readme.Name);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </caption>\r\n                    <tbody>\r\n            " +
"            <tr>\r\n                            <td>\r\n");

WriteLiteral("                                ");

            
            #line 119 "..\..\Views\Repository\Tree.cshtml"
                           Write(Html.Partial("_BlobPreview", Model.Readme));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                        </tr>\r\n             " +
"       </tbody>\r\n                </table>\r\n            </div>\r\n");

            
            #line 125 "..\..\Views\Repository\Tree.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 127 "..\..\Views\Repository\Tree.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
